#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

nitrogen --restore &

#transparencia
compton --config /home/hacker/.config/compton/compton.conf &


bspc monitor -d  II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off




bspc control --subscribe | while read -a msg; do
    case "${msg[0]}" in
        # Increase brightness
        XF86MonBrightnessUp)
            xbacklight -inc 10
            ;;
        # Decrease brightness
        XF86MonBrightnessDown)
            xbacklight -dec 10
            ;;
    esac
done

